add page-markup-function
Milosska/filmoteka pull request #10
Opened 2023-02-03 18:50 UTC by IrynaVal

В main.html додала кнопку для перевірки роботи функції (код закоментований)

2023-02-03 20:52 UTC, Milosska requested changes

2023-02-03 20:52 UTC, Milosska commented on src/js/components/markup-render.js
> +function onFetchError() {
Тут прописати console.log(error)

2023-02-03 20:52 UTC, Milosska commented on src/js/components/markup-render.js
> +// https://api.themoviedb.org/3/trending/movie/day?api_key=51114562faac57108ae3113fba230ec4&page=2
Продублювати використання колбек-функції для відправки запиту через натискання клавіші "Enter"

2023-02-03 20:52 UTC, Milosska commented on src/js/components/markup-render.js
> +function renderPageMarkup(evt, page=5) {
1) Чому 5? Може краще page=1 (бо 5 сторінок може і не бути). А так за замовчуванням завжди буде 1ша сторінка, а за необхідності можна буде передати інше значення.
2) Перед page поставити параметр query

2023-02-03 20:52 UTC, Milosska commented on src/partials/main.html
> +    <!-- <button class="btn" type="button">Render film cards</button> -->
Прибрати коментар)
Header, в принципі, вже прописаний, можна відразу до кнопки пошуку прив'язати

2023-02-03 20:52 UTC, Milosska commented on src/js/components/markup-render.js
> +  fetchInfo('keyword', 'dog', page).then(data => {
Замість "dog" передавати query (без лапок, як змінну)

2023-02-03 21:08 UTC, IrynaVal commented on src/js/components/markup-render.js
> +function onFetchError() {
написала

2023-02-03 21:30 UTC, IrynaVal commented on src/js/components/markup-render.js
> +  fetchInfo('keyword', 'dog', page).then(data => {
є

2023-02-03 21:36 UTC, IrynaVal commented on src/partials/main.html
> +    <!-- <button class="btn" type="button">Render film cards</button> -->
прив'язала

2023-02-03 22:05 UTC, IrynaVal commented on src/js/components/markup-render.js
> +// https://api.themoviedb.org/3/trending/movie/day?api_key=51114562faac57108ae3113fba230ec4&page=2
зробила

2023-02-04 11:44 UTC, Milosska approved these changes

2023-02-04 11:44 UTC, merged