Feature/modal.css
Milosska/filmoteka pull request #7
Opened 2023-02-03 13:05 UTC by Luidmyla007

2023-02-03 15:09 UTC, Milosska requested changes

2023-02-03 15:09 UTC, Milosska commented on src/js/components/modal.js
> +// function onModalOpen(event) {
Прибрати всі зайві коментарі з коду

2023-02-03 15:09 UTC, Milosska commented on src/js/components/modal.js
> +//          myOverlay.hidden = true;
Створити функцію hideAll() і туди перенести наступний шматок коду:
 myOverlay.hidden = true; 
myModal.hidden = true;
modalTeam.hidden = true;

Потім у кожному з івент-лісенерів на закриття просто викликати цю функцію.

2023-02-03 18:14 UTC, Milosska approved these changes

2023-02-03 18:14 UTC, merged

2023-02-04 07:28 UTC, Luidmyla007 commented on src/js/components/modal.js
> +// function onModalOpen(event) {
+

2023-02-04 07:29 UTC, Luidmyla007 commented
+